Add Schmidtke-2014-ValenceArousal
concepticon/norare-data pull request #225
Opened 2024-10-28 11:13 UTC by MiraAhmedovic

Adding Schmidtke-2014-ValenceArousal based on "ANGST: Affective norms for German sentiment terms, derived from the affective norms for English words" by Schmidtke et al. (2014), closes #218

2024-10-29 06:42 UTC, AnnikaTjuka requested changes
I left some comments mainly requesting changes in the `datasets.tsv` file. If you have questions about how to integrate the citations, let me know and I can explain it in more detail on Wednesday.

2024-10-29 06:42 UTC, AnnikaTjuka commented on datasets.tsv
> +Schmidtke-2014-ValenceArousal	Schmidtke, David S. and Schröder, Tobias and Jacobs, Arthur M. and Conrad, Markus	2014	ratings	German	German	https://doi.org/10.3758/s13428-013-0426-y	Schmidtke2014	This
You could add the abbreviation "ANGST" as an alias in the last column.

2024-10-29 06:42 UTC, AnnikaTjuka commented on datasets.tsv
> +Schmidtke-2014-ValenceArousal	Schmidtke, David S. and Schröder, Tobias and Jacobs, Arthur M. and Conrad, Markus	2014	ratings	German	German	https://doi.org/10.3758/s13428-013-0426-y	Schmidtke2014	This
As the dataset name, I'd suggest Schmidtke-2014-AffectiveRatings because we already have similar datasets with the same type of data and this name in NoRaRe and there are more variables available than valence and arousal.

2024-10-29 06:42 UTC, AnnikaTjuka commented on datasets.tsv
> +Schmidtke-2014-ValenceArousal	Schmidtke, David S. and Schröder, Tobias and Jacobs, Arthur M. and Conrad, Markus	2014	ratings	German	German	https://doi.org/10.3758/s13428-013-0426-y	Schmidtke2014	This
I think we can change "sentiment terms" to "words". The first item in the list is "Kuh" which does not express a sentiment.

2024-10-29 06:42 UTC, AnnikaTjuka commented on datasets/Schmidtke-2014-ValenceArousal/Schmidtke-2014-ValenceArousal.tsv-metadata.json
> +  "dc:title": "Ratings for valence, arousal, imageability, dominance and potency for German sentiment terms by Schmidtke et al. (2014)",
Again, change "sentiment terms" to "words". Same below.

2024-10-29 06:42 UTC, AnnikaTjuka commented on datasets.tsv
> +Schmidtke-2014-ValenceArousal	Schmidtke, David S. and Schröder, Tobias and Jacobs, Arthur M. and Conrad, Markus	2014	ratings	German	German	https://doi.org/10.3758/s13428-013-0426-y	Schmidtke2014	This
Please add a note on the rating scales that they use since they are different across the variables.

2024-10-29 06:42 UTC, AnnikaTjuka commented on datasets.tsv
> +Schmidtke-2014-ValenceArousal	Schmidtke, David S. and Schröder, Tobias and Jacobs, Arthur M. and Conrad, Markus	2014	ratings	German	German	https://doi.org/10.3758/s13428-013-0426-y	Schmidtke2014	This
Please add a citation to the BAWL and ANEW data in the description and then add the references to the `reference.bib` file. You can use the following example: [Hernández-Muñoz (2002)](:bib:Hernandez2002) This will establish a direct link to the reference. See also my comment on the `norare.tsv` file.

2024-10-29 06:42 UTC, AnnikaTjuka commented on norare.tsv
> +Schmidtke-2014-ValenceArousal	GERMAN_AROUSAL_MEAN_ANEW	mean	arousal		ratings	users	de		The mean rating of arousal of words on the list of  Affective Norms for English Words, translated into German. R
Please fill in the SOURCE column and the citation in the description. See `Izura-2005-499 SEMANTIC_CATEGORY` as an example.

2024-10-29 06:42 UTC, AnnikaTjuka commented on norare.tsv
> +Schmidtke-2014-ValenceArousal	GERMAN_AROUSAL_MEAN_BAWL	mean	arousal		ratings	users	de		The mean rating of arousal of words on the list of Berlin Affective Word List. Ratings were given on a 5-point s
Same as above.

2024-10-30 10:40 UTC, AnnikaTjuka requested changes
Just a few more tiny changes.

2024-10-30 10:40 UTC, AnnikaTjuka commented on datasets.tsv
> +Schmidtke-2014-AffectiveRatings	Schmidtke, David S. and Schröder, Tobias and Jacobs, Arthur M. and Conrad, Markus	2014	ratings	German	German	https://doi.org/10.3758/s13428-013-0426-y	Schmidtke2014	Th
Just a few minor changes to the description. I highlighted the proposed changes in **bold**:
This list contains ratings of valence, arousal, imageability, dominance and potency for German **words**. The study includes terms from the Affective Norms for English Words (ANEW) list ([Bradley and Lang 1999]**delete space**(:bib:Bradley1999)) as well as the Berlin Affective Word List (BAWL)  ([Vo et al. 2009](:bib:Vo2009)). Valence and imageability were rated on 7-point scales while potency, dominance and arousal for words **in** the ANEW list were rated on **a** 9-point scale. Arousal for words **in** the BAWL **list** was rated **on** a 5-point scale. The study contains additional variables, such as data on word frequency, grammatical class, number of letters, number of syllables, and number of orthographic neighbors, which come from other studies and were therefore not included in the data set here.

2024-10-30 10:40 UTC, AnnikaTjuka commented on references/references.bib
> +}
Have the references been added to the .bib file yet?

2024-11-04 08:33 UTC, MiraAhmedovic commented on references/references.bib
> +}
They are already part of references.bib, Vo2009 on lines 534-542 and Bradley1999 on lined 554-562

2024-11-04 10:25 UTC, AnnikaTjuka approved these changes
Everything looks great and this PR can be merged!

2024-11-04 10:26 UTC, merged